name: Gl1tchCraftBedWars
version: 1
main: me.gl1tchcraft.bedwars.Main
description: The Gl1tchCraft BedWars Plugin
commands:
    bedwars:
        usage: /<command>
        description: Bedwars command.
        aliases: [bw]
    global:
        usage: /<command>
        description: Global command.
        aliases: [g]
load: STARTUP